version: '3'

networks:
  recyclarr:
    name: recyclarr

volumes:
  radarr_nightly:
  sonarr_nightly:
  sonarr_v4:

services:
  radarr_nightly:
    image: ghcr.io/hotio/radarr:nightly
    container_name: radarr_nightly
    networks: [recyclarr]
    ports: [7878:7878]
    volumes:
      - radarr_nightly:/config
      - ./certs:/certs:ro
    environment:
      - TZ=America/Chicago

  sonarr_nightly:
    image: ghcr.io/hotio/sonarr:nightly
    container_name: sonarr_nightly
    networks: [recyclarr]
    ports: [8989:8989]
    volumes:
      - sonarr_nightly:/config
    environment:
      - TZ=America/Chicago

  sonarr_v4:
    image: ghcr.io/hotio/sonarr:v4
    container_name: sonarr_v4
    networks: [recyclarr]
    ports: [8990:8989]
    volumes:
      - sonarr_v4:/config
    environment:
      - TZ=America/Chicago
