# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Docker Image

on:
  release:
    types: [ published ]

env:
  dotnetVersion: "6.0"

jobs:
  build-docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Extract Image Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository }},ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ github.event.release.tag_name }}
            type=semver,pattern={{major}}.{{minor}},value=${{ github.event.release.tag_name }}
            type=semver,pattern={{major}},value=${{ github.event.release.tag_name }}

      - name: Build & Push Image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./docker
          build-args: |
            DOTNET_VERSION=${{ env.dotnetVersion }}
            REPOSITORY=${{ github.repository }}
            RELEASE_TAG=${{ github.event.release.tag_name }}
          platforms: linux/arm/v7,linux/arm64,linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
