# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build & Test

on:
  push:
    paths-ignore:
      - "wiki/**"
      - "**.md"

env:
  DOTNET_VERSION: "6.0"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # avoid shallow clone for GitVersion

      - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Test
        run: dotnet test src --configuration Release --logger GitHubActions

  build:
    name: Build
    needs: test
    runs-on: windows-latest # Must run on Windows so that version info gets properly set in host EXE. See: https://github.com/dotnet/runtime/issues/3828

    strategy:
      fail-fast: true
      matrix:
        runtime:
          - win-x64
          - win-arm64
          - linux-x64
          - linux-arm
          - linux-arm64
          - osx-x64
          - osx-arm64
          - linux-musl-x64
          - linux-musl-arm
          - linux-musl-arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # avoid shallow clone for GitVersion

      - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish
        shell: pwsh
        run: ci/Publish.ps1 ${{ matrix.runtime }}

      - name: Create Zip File
        shell: pwsh
        run: Compress-Archive publish/${{ matrix.runtime }}/* publish/trash-${{ matrix.runtime }}.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: trash-${{ matrix.runtime }}
          path: publish/trash-${{ matrix.runtime }}.zip

  smoke:
    name: Smoke Test
    needs: build
    runs-on: ${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: windows-latest
            runtime: win-x64
          - image: ubuntu-latest
            runtime: linux-x64
          - image: macos-latest
            runtime: osx-x64

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: trash-${{ matrix.runtime }}

      - name: Extract Zip File
        shell: pwsh
        run: Expand-Archive trash-${{ matrix.runtime }}.zip ./

      - name: Run Smoke Test
        shell: pwsh
        run: ci/SmokeTest.ps1 ./trash

  release:
    name: Release
    needs: smoke
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # avoid shallow clone for GitVersion
          # token: ${{ secrets.GITHUB_TOKEN }} # Allows git push

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: 5.x

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0
        id: gitversion

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: publish

      - name: Extract Changelog
        id: changelog
        uses: ffurrer2/extract-release-notes@v1

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          files: publish/**/trash-*.zip
          body: ${{ steps.changelog.outputs.release_notes }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: ${{ steps.gitversion.outputs.preReleaseTag != '' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      #- name: Login to DockerHub
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }} #${{ github.repository }},ghcr.io/${{ github.repository }}
          tags: type=ref,event=tag

      - name: Build & Push Image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./docker
          build-args: |
            DOTNET_VERSION=${{ env.DOTNET_VERSION }}
            REPOSITORY=${{ github.repository }}
            VERSION=${{ github.ref_name }}
          platforms: linux/arm/v7,linux/arm64,linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
