# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Docker Retention

on:
  workflow_dispatch: # TEMP
  schedule:
    - cron: '0 0 * * *'

jobs:
  retention:
    name: Enforce Retention Policy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch multi-platform package version SHAs
        id: multi-arch-digests
        run: |
          shas="$(pwsh ci/Get-DockerTagSHAs.ps1)"
          echo "shas=$shas" >> $GITHUB_OUTPUT

      - name: Delete old pre-release images
        uses: snok/container-retention-policy@v3.0.0
        with:
          image-names: recyclarr
          account: recyclarr
          image-tags: '*-dev.*'
          token: ${{ secrets.GITHUB_TOKEN }}
          cut-off: 1w
          keep-n-most-recent: 1
          skip-shas: ${{ steps.multi-arch-digests.outputs.shas }}
          dry-run: true # TEMP
